### ISSUE TITLE
Deprecated V8 APIs

### ISSUE THREAD

**Issue by Larry1123** [7THStage/idigdoge#2]
scrypt node.cc can not compile with the latest version of node

```
gyp info it worked if it ends with ok
gyp info using node-gyp@0.12.2
gyp info using node@0.11.11 | linux | x64
gyp info spawn python
gyp info spawn args [ '/CoinMine/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/CoinMine/scrypt/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/CoinMine/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/root/.node-gyp/0.11.11/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/root/.node-gyp/0.11.11',
gyp info spawn args   '-Dmodule_root_dir=/CoinMine/scrypt',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
../node.cc:11:28: error: 'Arguments' does not name a type
../node.cc:11:39: error: ISO C++ forbids declaration of 'args' with no type [-fpermissive]
/root/.node-gyp/0.11.11/deps/v8/include/v8.h: In function 'v8::Handle<v8::Value> Method(const int&)':
/root/.node-gyp/0.11.11/deps/v8/include/v8.h:768:13: error: 'v8::HandleScope::HandleScope()' is private
../node.cc:12:14: error: within this context
../node.cc:14:11: error: request for member 'Length' in 'args', which is of non-class type 'const int'
../node.cc:19:13: error: invalid types 'const int[int]' for array subscript
../node.cc:24:61: error: invalid types 'const int[int]' for array subscript
../node.cc:29:9: error: expected primary-expression before '*' token
../node.cc:29:10: error: 'bufferOut' was not declared in this scope
../node.cc: In function 'void init(v8::Handle<v8::Object>)':
../node.cc:35:72: error: invalid conversion from 'v8::Handle<v8::Value> (*)(const int&)' to 'v8::FunctionCallback {aka void (*)(const v8::FunctionCallbackInfo<v8::Value>&)}' [-fpermissive]
/root/.node-gyp/0.11.11/deps/v8/include/v8.h:3346:34: error:   initializing argument 1 of 'static v8::Local<v8::FunctionTemplate> v8::FunctionTemplate::New(v8::FunctionCallback, v8::Handle<v8::Value>, v8::Handle<v8::Signature>, int)' [-fpermissive]
../node.cc: In function 'v8::Handle<v8::Value> Method(const int&)':
../node.cc:32:1: warning: control reaches end of non-void function [-Wreturn-type]
make[1]: *** [Release/obj.target/scrypt/node.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/CoinMine/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:107:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:879:12)
gyp ERR! System Linux 2.6.32-042stab084.17
gyp ERR! command "node" "/CoinMine/node_modules/.bin/node-gyp" "configure" "build"
gyp ERR! cwd /CoinMine/scrypt
gyp ERR! node -v v0.11.11
gyp ERR! node-gyp -v v0.12.2
gyp ERR! not ok
```

**Comment by Larry1123** [comment]
I was able to downgrade my node version, but still that is a valid issue for 0.11.11

**Comment by 7THStage** [comment]
Because 11.X is still marked unstable, I haven't even touched it yet. Since you knew what the problem was, do you know how to fix it? I'll be the first to admit that C and C++ aren't my forte.

**Comment by Larry1123** [comment]
I am a Java Coder myself I have never touched Node before trying to setup a Nyan version of idigdoge. But from what I can tell they changed how it that api works, and from what I have found there is no official doc for the change in the api, I could only guess that when it is made stable that it would then have doc written for it.
