### ISSUE TITLE
Error: ERR wrong number of arguments for 'set' command

### ISSUE THREAD

**Issue by lukespragg** [7THStage/idigdoge#9]
I get this when attempting to connect to the site. I noticed that redis.js refers to config.redis, but that doesn't even exist in the config.js file. Am I missing something?

``` ruby
Error: ERR wrong number of arguments for 'set' command
at HiredisReplyParser.execute (/var/www/public/mine/node_modules/redis/lib/parser/hiredis.js:30:33
at RedisClient.on_data (/var/www/public/mine/node_modules/redis/index.js:534:27)
at Socket.<anonymous> (/var/www/public/mine/node_modules/redis/index.js:91:14)
at Socket.EventEmitter.emit (events.js:95:17)
at Socket.<anonymous> (_stream_readable.js:746:14)
at Socket.EventEmitter.emit (events.js:92:17)
at emitReadable_ (_stream_readable.js:408:10)
at emitReadable (_stream_readable.js:404:5)
at readableAddChunk (_stream_readable.js:165:9)
at Socket.Readable.push (_stream_readable.js:127:10)
```

Running node v0.10.26 and redis-server v2.4.16.

**Comment by 7THStage** [comment]
Line 6 in `redis.js` just makes it so if anyone needs to connect to a Redis server running on another server or a nonstandard port can do so. I forgot to include it in the config file, but the handy `|| ''` means it will just default to `localhost:6379` if it's not there.

My development and production environments are using Node versions 0.10.3 and 0.10.20 and Redis version 2.8.3 on both. I did some searching, and it appears that you might need to update Redis, [as your version isn't officially supported by `node_redis`](https://github.com/mranney/node_redis/issues/523). A lot of the repos don't seem to keep Node or Redis up to date, so I recommend [downloading and installing from source](http://redis.io/download).

If upgrading Redis doesn't fix the problem, I'll need to know what causes it. There's only four times in the project `set` is used, so hopefully it won't be too hard to track down!

**Comment by lukespragg** [comment]
That seems to have done the trick, thanks! I'm not sure how I missed that I was using an older Redis install.
